from typing import Dict, List, Optional
import json


class DoctorAgent:
    """
    LLM-powered doctor assistant.

    Capabilities:
    - Conversational follow-up questioning
    - Nurse-style case summarization
    - Patient & Doctor report generation
    - SOAP → JSON (EMR ready)
    - Safety-first (NO diagnosis, NO prescriptions)
    """

    def __init__(self, llm_client):
        self.llm = llm_client

    # --------------------------------------------------
    # 1. Dynamic Follow-up Questioning
    # --------------------------------------------------
    def ask_next_question(
        self,
        conversation_history: List[Dict],
        confidence: float
    ) -> Optional[str]:

        if confidence >= 0.85:
            return None

        if len(conversation_history) >= 6:
            return None

        prompt = self._question_prompt(conversation_history)
        response = self.llm.generate(prompt)

        return response.strip() if response else None

    # --------------------------------------------------
    # 2. Case Summarization
    # --------------------------------------------------
    def summarize_case(
        self,
        conversation_history: List[Dict]
    ) -> str:

        prompt = self._summary_prompt(conversation_history)
        return self.llm.generate(prompt).strip()

    # --------------------------------------------------
    # 3. Patient + Doctor Reports
    # --------------------------------------------------
    def generate_reports(
        self,
        ml_report: Dict,
        conversation_summary: str
    ) -> Dict[str, str]:

        patient_prompt = self._patient_report_prompt(
            ml_report=ml_report,
            summary=conversation_summary
        )

        doctor_prompt = self._doctor_report_prompt(
            ml_report=ml_report,
            summary=conversation_summary
        )

        return {
            "patient_report": self.llm.generate(patient_prompt).strip(),
            "doctor_report": self.llm.generate(doctor_prompt).strip(),
        }

    # --------------------------------------------------
    # 4. SOAP → JSON (EMR Ready)
    # --------------------------------------------------
    def generate_soap_json(
        self,
        ml_report: Dict,
        conversation_summary: str
    ) -> Dict:
        """
        Generates a STRICT JSON SOAP note.
        """

        prompt = self._soap_json_prompt(
            ml_report=ml_report,
            summary=conversation_summary
        )

        response = self.llm.generate(prompt)

        try:
            return json.loads(response)
        except Exception:
            return {
                "error": "Invalid JSON generated by LLM",
                "raw_output": response
            }

    # ==================================================
    # PROMPTS
    # ==================================================

    def _soap_json_prompt(self, ml_report: Dict, summary: str) -> str:
        return f"""
You are generating a STRICT JSON clinical SOAP note.

Conversation Summary:
{summary}

ML Risk Assessment:
{ml_report}

Output MUST be valid JSON only.
NO markdown.
NO explanation.
NO trailing text.

JSON Schema:
{{
  "subjective": {{
    "chief_complaint": "",
    "history_of_present_illness": "",
    "duration": "",
    "associated_symptoms": [],
    "relevant_negatives": []
  }},
  "objective": {{
    "vitals": {{}},
    "labs": {{}},
    "ml_risk_scores": {{}}
  }},
  "assessment": {{
    "risk_stratification": [],
    "clinical_impressions": []
  }},
  "plan": {{
    "monitoring": [],
    "investigations": [],
    "referrals": [],
    "lifestyle_guidance": []
  }},
  "disclaimer": ""
}}

Rules:
- No diagnosis
- No prescriptions
- Use risk-based wording only
- Include ML risk scores numerically
- Use empty arrays if unknown
"""

    def _question_prompt(self, history: List[Dict]) -> str:
        return f"""
You are a calm, polite, empathetic medical doctor.

Conversation so far:
{history}

Rules:
- Ask ONLY ONE follow-up question
- Start politely and neutrally
- Sound human and reassuring
- Do NOT diagnose
- Do NOT prescribe
- Avoid repeating questions
"""

    def _summary_prompt(self, history: List[Dict]) -> str:
        return f"""
Summarize the consultation into clinical notes.

Conversation:
{history}

Include:
- Chief complaint
- Duration
- Key symptoms
- Relevant negatives
- Risk factors

Rules:
- No assumptions
- No diagnoses
"""

    def _patient_report_prompt(self, ml_report: Dict, summary: str) -> str:
        return f"""
Explain findings to a patient in simple language.

Summary:
{summary}

Risk Assessment:
{ml_report}

Rules:
- Reassure if low risk
- Calm explanation if elevated risk
- Lifestyle guidance only
- No diagnoses
- No medications
"""

    def _doctor_report_prompt(self, ml_report: Dict, summary: str) -> str:
        return f"""
Write a doctor-facing SOAP note.

Summary:
{summary}

ML Risk:
{ml_report}

Rules:
- No diagnosis
- No prescriptions
- Guideline-based language
- Include disclaimer
"""
